{
 "title": "HSAK",
 "description": "Needs a better name than HSAK",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Service Broker Error Rate by Type ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(code, backend) (rate(faultmonkey_upstream_errors[1m]))",
     "legendFormat": "{{code}}-{{backend}}"
    }
   ]
  },
  {
   "title": "Service Broker Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(upstream) (rate(faultmonkey_upstream_requests[1m]))",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "Search Brokered Backends",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(faultmonkey_upstream_requests{upstream=\"search\"}[1m])",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Search Brokered Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(faultmonkey_upstream_requests{upstream=\"search\"}[1m])",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Alexa1m Brokered Backends",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(faultmonkey_upstream_requests{upstream=\"alexa1m\"}[1m])",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Alexa1m Brokered Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(faultmonkey_upstream_requests{upstream=\"alexa1m\"}[1m])",
     "legendFormat": "{{backend}}"
    }
   ]
  }
 ]
}