{
 "title": "HSAK",
 "description": "Needs a better name than HSAK",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Service Broker Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(faultmonkey_broker_requests[1m])",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Gateway Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(faultmonkey_gateway_requests[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Alexa1m Backends",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(faultmonkey_broker_requests[1m])",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Service Broker Revenue by Customer (£)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (customer) (faultmonkey_broker_cost / 100)",
     "legendFormat": "{{customer}}"
    }
   ]
  }
 ]
}